export const AUTH_SUCCESS = 'AUTH_SUCCESS';  // 注册或登录成功
export const ERROR_MSG = 'ERROR_MSG';  // 错误提示信息
export const RECEIVE_USER ='RECEIVE_USER'; // 接收用户
export const RESET_USER ='RESET_USER'; // 重置用户
export const RECEIVE_USER_LIST = 'RECEIVE_USER_LIST'; // 获取用户列表
export const RECEIVE_MSG_LIST = 'RECEIVE_MSG_LIST'; // 接收所有相关消息
export const RECEIVE_MSG = 'RECEIVE_MSG';  // 接收一条消息
export const MSG_READ = 'MSG_READ'; // 查看消息
export const RECEIVE_HOUSING_INFO = 'RECEIVE_HOUSING_INFO'; // 获取房源信息
export const CHANGE_HOUSING = 'CHANGE_HOUSING'; // 改变房源信息
export const DELETE_HOUSING = 'DELETE_HOUSING'; // 删除房源信息
export const GET_INFO =　'GET_INFO';　// 获取发布信息
export const DELETE_INFO = 'DELETE_INFO'; // 删除发布的信息
export const ZUKE_HOUSING = 'ZUKE_HOUSING'; // 获取租客房源
export const GET_ALL_COMMENT = 'GET_ALL_COMMENT'; // 获取所有评论
export const ADD_COMMENT = 'ADD_COMMENT'; // 新增评论
export const DELETE_COMMENT = 'DELETE_COMMENT'; // 删除评论
export const GET_REJECT_ID = 'GET_REJECT_ID'; // 获取自身屏蔽id
export const GET_REJECT_ID_OTHER = 'GET_REJECT_ID_OTHER'; // 获取他人屏蔽id
