export const AUTH_SUCCESS = 'AUTH_SUCCESS';  //注册或登录成功
export const ERROR_MSG = 'ERROR_MSG';  //错误提示信息
export const RECEIVE_USER ='RECEIVE_USER'; //接收用户
export const RESET_USER ='RESET_USER'; //重置用户
export const RECEIVE_USER_LIST = 'RECEIVE_USER_LIST'; //获取用户列表
export const RECEIVE_MSG_LIST = 'RECEIVE_MSG_LIST'; //接收所有相关消息
export const RECEIVE_MSG = 'RECEIVE_MSG';  //接收一条消息
export const MSG_READ = 'MSG_READ'; //查看消息
export const RECEIVE_HOUSING_INFO = 'RECEIVE_HOUSING_INFO'; // 获取房源信息
